#bit compress spix4 speed up
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property PACKAGE_PIN G25 [get_ports uart_txd]
set_property PACKAGE_PIN L27 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rxd]

set_property PACKAGE_PIN AD26 [get_ports rst]
set_property PACKAGE_PIN AC24 [get_ports sys_mmcm_sel_cmd_raw]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports sys_mmcm_sel_cmd_raw]

create_clock -period 4.000 [get_ports gty127_clk_p]
set_property PACKAGE_PIN R29 [get_ports gty127_clk_p]
set_property PACKAGE_PIN G27 [get_ports {user_led[5]}]
set_property PACKAGE_PIN G26 [get_ports {user_led[4]}]
set_property PACKAGE_PIN H27 [get_ports {user_led[3]}]
set_property PACKAGE_PIN H26 [get_ports {user_led[2]}]
set_property PACKAGE_PIN J26 [get_ports {user_led[1]}]
set_property PACKAGE_PIN AC26 [get_ports {user_led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {user_led[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {user_led[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {user_led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {user_led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {user_led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {user_led[0]}]

set_property PACKAGE_PIN A12 [get_ports {rf_out_en[3]}]
set_property PACKAGE_PIN A13 [get_ports {rf_out_en[2]}]
set_property PACKAGE_PIN C13 [get_ports {rf_out_en[1]}]
set_property PACKAGE_PIN D13 [get_ports {rf_out_en[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rf_out_en[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rf_out_en[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rf_out_en[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rf_out_en[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports ad9144_irq]
set_property IOSTANDARD LVCMOS18 [get_ports ad9144_tx_en0]
set_property IOSTANDARD LVCMOS18 [get_ports ad9144_tx_en1]
set_property PACKAGE_PIN B9 [get_ports ad9144_irq]
set_property PACKAGE_PIN E8 [get_ports ad9144_tx_en0]
set_property PACKAGE_PIN F8 [get_ports ad9144_tx_en1]
create_clock -period 4.000 [get_ports gty224_clk_p]
create_clock -period 4.000 [get_ports gty225_clk_p]
create_clock -period 4.000 [get_ports gty226_clk_p]
create_clock -period 4.000 [get_ports gty227_clk_p]
create_clock -period 5.000 [get_ports sysclk_p]
create_clock -period 4.000 -waveform {0.000 2.000} [get_ports coreclk_p]
set_property PACKAGE_PIN AF6 [get_ports gty224_clk_p]
set_property PACKAGE_PIN AB6 [get_ports gty225_clk_p]
set_property PACKAGE_PIN V6 [get_ports gty226_clk_p]
set_property PACKAGE_PIN P6 [get_ports gty227_clk_p]
#set_property PACKAGE_PIN F18 [get_ports sysclk_p]
set_property PACKAGE_PIN AJ23 [get_ports sysclk_p]
set_property IOSTANDARD LVDS [get_ports sysclk_p]
set_property IOSTANDARD LVDS [get_ports sysclk_n]
set_property PACKAGE_PIN AG12 [get_ports coreclk_p]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports coreclk_n]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports coreclk_p]

#set_property IOSTANDARD LVDS [get_ports coreclk_n]
#set_property IOSTANDARD LVDS [get_ports coreclk_p]

set_property PACKAGE_PIN C17 [get_ports lmk048_ld1]
set_property PACKAGE_PIN B17 [get_ports lmk048_ld2]
set_property PACKAGE_PIN W24 [get_ports ads54j60_reset]
set_property PACKAGE_PIN G20 [get_ports ads54j69_reset]
set_property PACKAGE_PIN D14 [get_ports lmk048_sync]
set_property IOSTANDARD LVCMOS18 [get_ports lmk048_ld1]
set_property IOSTANDARD LVCMOS18 [get_ports lmk048_ld2]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j60_reset]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j69_reset]
set_property IOSTANDARD LVCMOS18 [get_ports lmk048_sync]
set_property PACKAGE_PIN AG11 [get_ports sysrefclk_p]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports sysrefclk_p]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports sysrefclk_n]
set_property LOC GTHE3_CHANNEL_X1Y3 [get_cells {u_adda_top/adda_top_i/ads54j60_sub/jesd204_phy_0/inst/jesd204_phy_block_i/adda_top_jesd204_phy_0_2_gt_i/inst/gen_gtwizard_gthe3_top.adda_top_jesd204_phy_0_2_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[3].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN AJ4 [get_ports {ads54j60_A_p[3]}]
set_property LOC GTHE3_CHANNEL_X1Y2 [get_cells {u_adda_top/adda_top_i/ads54j60_sub/jesd204_phy_0/inst/jesd204_phy_block_i/adda_top_jesd204_phy_0_2_gt_i/inst/gen_gtwizard_gthe3_top.adda_top_jesd204_phy_0_2_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[3].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN AK2 [get_ports {ads54j60_A_p[2]}]
set_property PACKAGE_PIN AM2 [get_ports {ads54j60_A_p[1]}]
set_property PACKAGE_PIN AP2 [get_ports {ads54j60_A_p[0]}]
set_property PACKAGE_PIN AB2 [get_ports {ads54j60_B_p[3]}]
set_property PACKAGE_PIN AD2 [get_ports {ads54j60_B_p[2]}]
set_property PACKAGE_PIN AF2 [get_ports {ads54j60_B_p[1]}]
set_property PACKAGE_PIN AH2 [get_ports {ads54j60_B_p[0]}]
set_property LOC GTHE3_CHANNEL_X1Y9 [get_cells {u_adda_top/adda_top_i/ads54j69_sub/jesd204_phy_0/inst/jesd204_phy_block_i/adda_top_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe3_top.adda_top_jesd204_phy_0_0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[3].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN V2 [get_ports {ads54j69_A_p[1]}]
set_property LOC GTHE3_CHANNEL_X1Y8 [get_cells {u_adda_top/adda_top_i/ads54j69_sub/jesd204_phy_0/inst/jesd204_phy_block_i/adda_top_jesd204_phy_0_0_gt_i/inst/gen_gtwizard_gthe3_top.adda_top_jesd204_phy_0_0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[3].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN Y2 [get_ports {ads54j69_A_p[0]}]
set_property PACKAGE_PIN K2 [get_ports {ads54j69_B_p[1]}]
set_property PACKAGE_PIN M2 [get_ports {ads54j69_B_p[0]}]
set_property LOC GTHE3_CHANNEL_X0Y19 [get_cells {u_adda_top/adda_top_i/ad9144_sub/jesd204_phy_0/inst/jesd204_phy_block_i/adda_top_jesd204_phy_0_3_gt_i/inst/gen_gtwizard_gthe3_top.adda_top_jesd204_phy_0_3_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[4].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN B31 [get_ports {ad9144_da_p[7]}]
set_property LOC GTHE3_CHANNEL_X0Y18 [get_cells {u_adda_top/adda_top_i/ad9144_sub/jesd204_phy_0/inst/jesd204_phy_block_i/adda_top_jesd204_phy_0_3_gt_i/inst/gen_gtwizard_gthe3_top.adda_top_jesd204_phy_0_3_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[4].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN D31 [get_ports {ad9144_da_p[6]}]
set_property LOC GTHE3_CHANNEL_X0Y17 [get_cells {u_adda_top/adda_top_i/ad9144_sub/jesd204_phy_0/inst/jesd204_phy_block_i/adda_top_jesd204_phy_0_3_gt_i/inst/gen_gtwizard_gthe3_top.adda_top_jesd204_phy_0_3_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[4].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN G29 [get_ports {ad9144_da_p[5]}]
set_property LOC GTHE3_CHANNEL_X0Y16 [get_cells {u_adda_top/adda_top_i/ad9144_sub/jesd204_phy_0/inst/jesd204_phy_block_i/adda_top_jesd204_phy_0_3_gt_i/inst/gen_gtwizard_gthe3_top.adda_top_jesd204_phy_0_3_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[4].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST}]
set_property PACKAGE_PIN H31 [get_ports {ad9144_da_p[4]}]
set_property PACKAGE_PIN K31 [get_ports {ad9144_da_p[3]}]
set_property PACKAGE_PIN M31 [get_ports {ad9144_da_p[2]}]
set_property PACKAGE_PIN P31 [get_ports {ad9144_da_p[1]}]
set_property PACKAGE_PIN T31 [get_ports {ad9144_da_p[0]}]
set_property PACKAGE_PIN A9 [get_ports ad9144_cs]
set_property PACKAGE_PIN A10 [get_ports ad9144_miso]
set_property PACKAGE_PIN D8 [get_ports ad9144_mosi]
set_property PACKAGE_PIN C8 [get_ports ad9144_sclk]
set_property PACKAGE_PIN AA25 [get_ports ads54j60_cs]
set_property PACKAGE_PIN Y25 [get_ports ads54j60_sclk]
set_property PACKAGE_PIN W23 [get_ports ads54j60_sdin]
set_property PACKAGE_PIN Y21 [get_ports ads54j60_sdio]
set_property PACKAGE_PIN AA24 [get_ports ads54j60_syncse]
set_property PACKAGE_PIN H22 [get_ports ads54j69_cs]
set_property PACKAGE_PIN F22 [get_ports ads54j69_sclk]
set_property PACKAGE_PIN U29 [get_ports ads54j69_sdin]
set_property PACKAGE_PIN G22 [get_ports ads54j69_sdio]
set_property PACKAGE_PIN J23 [get_ports ads54j69_syncse]
set_property PACKAGE_PIN G10 [get_ports da_sync_out0_p]
set_property PACKAGE_PIN G9 [get_ports da_sync_out1_p]
set_property PACKAGE_PIN C14 [get_ports lmk048_clk]
set_property PACKAGE_PIN F15 [get_ports lmk048_cs]
set_property PACKAGE_PIN C18 [get_ports lmk048_mosi]


set_property IOSTANDARD LVCMOS18 [get_ports ad9144_cs]
set_property IOSTANDARD LVCMOS18 [get_ports ad9144_miso]
set_property IOSTANDARD LVCMOS18 [get_ports ad9144_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports ad9144_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j60_cs]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j60_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j60_sdin]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j60_sdio]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j60_syncse]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j69_cs]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j69_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j69_sdin]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j69_sdio]
set_property IOSTANDARD LVCMOS18 [get_ports ads54j69_syncse]
set_property IOSTANDARD LVCMOS18 [get_ports lmk048_clk]
set_property IOSTANDARD LVCMOS18 [get_ports lmk048_cs]
set_property IOSTANDARD LVCMOS18 [get_ports lmk048_mosi]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports da_sync_out0_p]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports da_sync_out1_p]

set_property MARK_DEBUG true [get_nets sys_mmcm_sel_cmd_buf]
set_property MARK_DEBUG true [get_nets sys_mmcm_sel_cmd]
set_property MARK_DEBUG true [get_nets sys_mmcm_sel]
set_property MARK_DEBUG true [get_nets sys_mmcm_rst]

set_property DIFF_TERM_ADV TERM_NONE [get_ports sysclk_p]
connect_debug_port dbg_hub/clk [get_nets clk]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 4 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk_in]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list sys_mmcm_rst]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list sys_mmcm_sel]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list sys_mmcm_sel_cmd]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list sys_mmcm_sel_cmd_buf]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk]
