"""Code generator — produces VHDL + Python code for new FPGA modules.

Generates:
- VHDL core entity (skeleton — signal processing logic must be filled by user)
- VHDL module wrapper (bus_handler + parameter_ram + core instantiation)
- Python hardware class (ModuleBase subclass)
- Python Qt NodeItem class (NodeItem subclass)
- Parameter schema
- Runtime registration injections
"""

from __future__ import annotations

import os
import json
import textwrap
from pathlib import Path

# Paths relative to this file
_BASE = Path(__file__).resolve().parent
_GENERATED = _BASE / "generated"
_MODULES_DIR = _GENERATED / "modules"
_PORT_MAP_FILE = _GENERATED / "port_map.json"
_HW_CLASSES_FILE = _GENERATED / "hw_classes.py"
_NODE_CLASSES_FILE = _GENERATED / "node_classes.py"
_SCHEMAS_FILE = _GENERATED / "schemas.py"

# VHDL Templates
VHDL_CORE_TEMPLATE = '''\
-- Generated by FPGA_Agent
-- Module: {module_name}

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.mypak.all;

entity {module_name} is
    generic(
        io_buf : buf_type := buf_for_io
    );
    port(
        clk             :   in  std_logic;
        rst             :   in  std_logic;
        core_param_in   :   in  std_logic_vector({size} - 1 downto 0);
{data_flow_ports}
        -- control ports
        auto_reset_in   :   in  std_logic
    );
end entity {module_name};

architecture behavioural of {module_name} is
    signal internal_rst         :   std_logic;
    signal enable_auto_reset    :   std_logic;
{internal_signals}
begin
{io_buffer_logic}

    internal_rst <= '1' when rst = '1' or (enable_auto_reset = '1' and auto_reset_in = '1') else '0';
end architecture behavioural;
'''

VHDL_MODULE_TEMPLATE = '''\
-- Generated by FPGA_Agent
-- Module wrapper for: {module_name}

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.mypak.all;

entity module_{module_name} is
    port(
        clk             :   in  std_logic;
        rst             :   in  std_logic;
        bus_en_in       :   in  std_logic;
        dbus_in         :   in  std_logic_vector(dbus_w - 1 downto 0);
        abus_in         :   in  std_logic_vector(abus_w - 1 downto 0);
        cbus_in         :   in  std_logic_vector(cbus_w - 1 downto 0);
        rsp_data_out    :   out std_logic_vector(rdbus_w - 1 downto 0);
        rsp_stat_out    :   out std_logic_vector(rsbus_w - 1 downto 0)
{data_flow_ports}
    );
end entity module_{module_name};

architecture structural of module_{module_name} is
    signal core_param       :   std_logic_vector({size} - 1 downto 0) := (others => '0');
    signal core_rst         :   std_logic := '1';

    signal ram_rst          :   std_logic := '1';
    signal handler_rst      :   std_logic := '1';

    signal wdata            :   std_logic_vector(dbus_w - 1 downto 0);
    signal waddr            :   std_logic_vector(abus_w - 1 downto 0);
    signal wmask            :   std_logic_vector(dbus_w - 1 downto 0);
    signal wval             :   std_logic;
    signal wen              :   std_logic;
    signal rdata            :   std_logic_vector(dbus_w - 1 downto 0);
    signal raddr            :   std_logic_vector(abus_w - 1 downto 0);
    signal rval             :   std_logic;
    signal ren              :   std_logic;
begin

    core_entity : entity work.{module_name} port map(
        clk             =>  clk,
        rst             =>  core_rst,
        core_param_in   =>  core_param
{core_port_map}
    );

    parameter_ram : entity work.parameter_ram_{size} generic map(
        ram_default     =>  x"00000000000000000000000000000000" &
                            x"00000000000000000000000000000000" &
                            x"00000000000000000000000000000000" &
                            x"00000000000000000000000000000000" &
                            x"00000000000000000000000000000000" &
                            x"00000000000000000000000000000000" &
                            x"00000000000000000000000000000000" &
                            x"00000000000000000000000000000000"
    )port map(
        clk             =>  clk,
        rst             =>  ram_rst,
        wdata_in        =>  wdata,
        waddr_in        =>  waddr,
        wmask_in        =>  wmask,
        wval_in         =>  wval,
        wen_in          =>  wen,
        rdata_out       =>  rdata,
        raddr_in        =>  raddr,
        rval_out        =>  rval,
        ren_in          =>  ren,
        ram_data_out    =>  core_param
    );

    bus_handler : entity work.bus_handler port map(
        clk             =>  clk,
        rst             =>  handler_rst,
        bus_en_in       =>  bus_en_in,
        dbus_in         =>  dbus_in,
        abus_in         =>  abus_in,
        cbus_in         =>  cbus_in,
        rsp_data_out    =>  rsp_data_out,
        rsp_stat_out    =>  rsp_stat_out,
        wdata_out       =>  wdata,
        waddr_out       =>  waddr,
        wmask_out       =>  wmask,
        wval_out        =>  wval,
        wen_out         =>  wen,
        rdata_in        =>  rdata,
        raddr_out       =>  raddr,
        rval_in         =>  rval,
        ren_out         =>  ren,
        ram_rst_out     =>  ram_rst,
        core_rst_out    =>  core_rst
    );
    handler_rst <= rst;

end architecture structural;
'''

PYTHON_HW_TEMPLATE = '''\
class Module{class_name}(ModuleBase):
    """{description}"""

    def __init__(self, bus_inst: Bus, name: str):
        super().__init__(bus_inst, name)
{parameter_list}
{alias_list}
'''

PYTHON_NODE_TEMPLATE = '''\
class Module{class_name}(NodeItem):
    """GUI node for {display_name}."""

    def __init__(self, component_name, index, position):
        if index == 0:
            name = "{short_name}"
        else:
            name = f"{short_name}{{index + 1}}"
        super().__init__(name, component_name, index, position,
                         {num_inputs}, {num_outputs})
        self.name = name
        self.height = {height}
        self.width = 128
        self.component_name = component_name
        self.display_name = f"{display_name}{{index + 1}}"
        self.index = index
        self.num_inputs = {num_inputs}
        self.num_outputs = {num_outputs}
        self.inputs = {inputs_list}
        self.outputs = {outputs_list}
        self.inputs_display_name = {inputs_display}
        self.outputs_display_name = {outputs_display}
        self.inputs_signals = {inputs_signals}
        self.outputs_signals = {outputs_signals}
        self.maxm = {max_instances}
        self.setPos(position)
        self.schema = {schema_var}
        self.free_mode = True
        self._params = {{}}
        self._init_params()
        self.setFlag(QGraphicsItem.ItemIsFocusable)
        self.setFlag(QGraphicsItem.ItemIsMovable)
        self.setFlag(QGraphicsItem.ItemIsSelectable)
        self.setFlag(QGraphicsItem.ItemSendsGeometryChanges)
        self._create_ports()

    def getmaxm(self):
        return self.maxm

    def param_schema(self):
        if self.free_mode:
            return [f for f in self.schema if f.get("free", True)]
        return self.schema
'''


class CodeGenerator:
    """Generate VHDL + Python for a new FPGA module from an LLM specification."""

    def __init__(self):
        self._generated_modules: dict[str, dict] = {}
        self._load_port_map()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, spec: dict) -> dict:
        """Generate all code files for a new module.

        Args:
            spec: module specification from the LLM generate_module tool call.
                  Required keys: module_name, display_name, description, inputs, outputs
                  Optional: params, max_instances

        Returns:
            {"success": True, "files": [...], "module_info": {...}}
        """
        module_name = spec["module_name"]
        display_name = spec["display_name"]
        description = spec.get("description", "")
        inputs = spec.get("inputs", [])
        outputs = spec.get("outputs", [])
        params = spec.get("params", [])
        max_instances = spec.get("max_instances", 2)

        # Validate
        if not module_name.isidentifier():
            return {"success": False,
                    "error": f"module_name '{module_name}' is not a valid identifier."}

        # Determine parameter RAM depth (min 8, power of 2)
        param_count = max(len(params), 8)
        ram_depth = 1
        while ram_depth < param_count:
            ram_depth *= 2
        ram_bits = ram_depth * 32  # total parameter RAM bit width

        # Allocate port numbers
        signal_in, signal_out, ctrl_in, ctrl_out = self._alloc_ports(inputs, outputs)

        # Generate files
        files_written = []

        # 1. VHDL core
        vhdl_core = self._gen_vhdl_core(module_name, description, inputs, outputs,
                                        params, ram_bits)
        core_path = self._write_module_file(module_name,
                                            f"{module_name}.vhdl", vhdl_core)
        files_written.append(str(core_path))

        # 2. VHDL module wrapper
        vhdl_mod = self._gen_vhdl_module(module_name, inputs, outputs, ram_bits)
        mod_path = self._write_module_file(module_name,
                                           f"module_{module_name}.vhdl", vhdl_mod)
        files_written.append(str(mod_path))

        # 3. Python hardware class
        hw_class = self._gen_python_hw(module_name, description, params)
        self._append_to_file(_HW_CLASSES_FILE, hw_class)
        files_written.append(str(_HW_CLASSES_FILE))

        # 4. Python NodeItem class
        node_class, class_name, short_name = self._gen_python_node(
            module_name, display_name, inputs, outputs, max_instances, params)
        self._append_to_file(_NODE_CLASSES_FILE, node_class)
        files_written.append(str(_NODE_CLASSES_FILE))

        # 5. Schema
        schema_code = self._gen_schema(class_name, params)
        self._append_to_file(_SCHEMAS_FILE, schema_code)
        files_written.append(str(_SCHEMAS_FILE))

        # 6. Update port map
        self._save_port_map()

        # Store for runtime registration
        module_info = {
            "display_name": display_name,
            "module_name": module_name,
            "internal_names": [short_name, f"{short_name}2"],
            "max_instances": max_instances,
            "purpose": description,
            "category": "generated",
            "inputs": inputs,
            "outputs": outputs,
            "direct_params": params,
            "indirect_params": [],
            "node_class_name": class_name,
            "hw_class_name": f"Module{class_name}",
            "signal_in_ports": signal_in,
            "signal_out_ports": signal_out,
            "ctrl_in_ports": ctrl_in,
            "ctrl_out_ports": ctrl_out,
        }
        self._generated_modules[display_name] = module_info

        return {
            "success": True,
            "module_name": module_name,
            "display_name": display_name,
            "files": files_written,
            "note": (
                "VHDL core logic is a SKELETON — the signal processing code "
                "between the 'use_input_buffer' and 'use_output_buffer' blocks "
                "must be filled in by a hardware engineer.  The Python classes "
                "are ready for use after restarting the application."
            ),
        }

    def register_runtime(self, canvas_bridge) -> bool:
        """Inject all generated modules into the running application.

        Monkey-patches module_factory, resolve_port_number, etc.
        so that generated modules become available for create_module.
        """
        if not self._generated_modules:
            return False

        try:
            import qt_module
            import qt_ui_utils

            for display_name, info in self._generated_modules.items():
                class_name = info["node_class_name"]
                max_inst = info["max_instances"]

                # Try to import the generated class
                try:
                    import importlib, sys
                    # Ensure generated package is importable
                    gen_path = str(_GENERATED)
                    if gen_path not in sys.path:
                        sys.path.insert(0, gen_path)

                    node_mod = importlib.import_module("node_classes")
                    generated_cls = getattr(node_mod, f"Module{class_name}", None)
                    if generated_cls is None:
                        continue
                except (ImportError, KeyError):
                    # Class not yet importable — will work after restart
                    continue

                # Register in module_factory
                qt_module.module_factory[display_name] = generated_cls
                if hasattr(qt_module, 'module_maxm'):
                    qt_module.module_maxm[display_name] = max_inst

                # Register in view instance dicts
                view = canvas_bridge._view
                view._used_indices[display_name] = set()
                view._maxnum[display_name] = max_inst

                # Patch resolve_port_number
                signal_in = info.get("signal_in_ports", {})
                signal_out = info.get("signal_out_ports", {})
                ctrl_in = info.get("ctrl_in_ports", {})
                ctrl_out = info.get("ctrl_out_ports", {})
                short_names = info.get("internal_names", [])

                _original_resolve = qt_ui_utils.resolve_port_number

                def _make_patched(orig, sig_in, sig_out, c_in, c_out, snames):
                    def patched(node_name, port_index, role):
                        result = orig(node_name, port_index, role)
                        if result is not None:
                            return result
                        # Check generated modules
                        if role == "in" and node_name in snames:
                            combined = {**sig_in, **c_in}
                            return combined.get(port_index)
                        if role == "out" and node_name in snames:
                            combined = {**sig_out, **c_out}
                            return combined.get(port_index)
                        return None
                    return patched

                qt_ui_utils.resolve_port_number = _make_patched(
                    qt_ui_utils.resolve_port_number,
                    signal_in, signal_out, ctrl_in, ctrl_out, short_names,
                )

            return True
        except Exception:
            return False

    # ------------------------------------------------------------------
    # Internal generators
    # ------------------------------------------------------------------

    def _gen_vhdl_core(self, name, desc, inputs, outputs, params, ram_bits):
        """Generate VHDL core entity skeleton."""
        # Data flow ports
        port_lines = []
        for p in inputs:
            port_lines.append(f"        {p['name'].lower():<16}:   in  std_logic_vector(15 downto 0);")
        for p in outputs:
            port_lines.append(f"        {p['name'].lower():<16}:   out std_logic_vector(15 downto 0);")

        data_flow = "\n".join(port_lines) if port_lines else "        -- (no data flow ports)"

        # Internal signals (skeleton)
        sig_lines = []
        for p in inputs:
            sig_lines.append(f"    signal {p['name'].lower()}_buf  : signed(15 downto 0);")
        for p in outputs:
            sig_lines.append(f"    signal {p['name'].lower()}_buf  : signed(15 downto 0) := (others => '0');")
        internals = "\n".join(sig_lines) if sig_lines else "    -- (no internal signals)"

        # IO buffer logic (skeleton)
        io_buf = self._gen_io_buffer(name, inputs, outputs)

        return VHDL_CORE_TEMPLATE.format(
            module_name=name,
            size=ram_bits,
            data_flow_ports=data_flow,
            internal_signals=internals,
            io_buffer_logic=io_buf,
        )

    def _gen_io_buffer(self, name, inputs, outputs):
        """Generate the VHDL io buffer boilerplate."""
        lines = []
        lines.append("    use_input_buffer : if io_buf = buf_for_io or io_buf = buf_i_only generate")
        lines.append("        process(clk)")
        lines.append("        begin")
        lines.append("            if rising_edge(clk) then")
        lines.append("                if internal_rst = '1' then")
        for p in inputs:
            lines.append(f"                    {p['name'].lower()}_buf <= (others => '0');")
        lines.append("                else")
        for p in inputs:
            lines.append(f"                    {p['name'].lower()}_buf <= signed({p['name'].lower()});")
        lines.append("                end if;")
        lines.append("            end if;")
        lines.append("        end process;")
        lines.append("    end generate;")
        lines.append("")
        lines.append("    no_input_buffer : if io_buf = buf_o_only or io_buf = buf_none generate")
        for p in inputs:
            lines.append(f"        {p['name'].lower()}_buf <= signed({p['name'].lower()});")
        lines.append("    end generate;")
        lines.append("")

        # Output buffer
        lines.append("    use_output_buffer : if io_buf = buf_for_io or io_buf = buf_o_only generate")
        lines.append("        process(clk)")
        lines.append("        begin")
        lines.append("            if rising_edge(clk) then")
        lines.append("                if internal_rst = '1' then")
        for p in outputs:
            lines.append(f"                    {p['name'].lower()} <= (others => '0');")
        lines.append("                else")
        for p in outputs:
            lines.append(f"                    {p['name'].lower()} <= std_logic_vector({p['name'].lower()}_buf);")
        lines.append("                end if;")
        lines.append("            end if;")
        lines.append("        end process;")
        lines.append("    end generate;")
        lines.append("")
        lines.append("    no_output_buffer : if io_buf = buf_i_only or io_buf = buf_none generate")
        for p in outputs:
            lines.append(f"        {p['name'].lower()} <= std_logic_vector({p['name'].lower()}_buf);")
        lines.append("    end generate;")

        return "\n".join(lines)

    def _gen_vhdl_module(self, name, inputs, outputs, ram_bits):
        """Generate VHDL module wrapper."""
        # Data flow port declarations
        port_lines = []
        for p in inputs:
            port_lines.append(f"        {p['name'].lower():<16}:   in  std_logic_vector(15 downto 0);")
        for p in outputs:
            port_lines.append(f"        {p['name'].lower():<16}:   out std_logic_vector(15 downto 0);")
        data_flow = "\n".join(port_lines) if port_lines else ""

        # Core port map connections
        map_lines = []
        for p in inputs:
            map_lines.append(f"        {p['name'].lower():<16}=>  {p['name'].lower()},")
        for p in outputs:
            map_lines.append(f"        {p['name'].lower():<16}=>  {p['name'].lower()},")
        core_map = "\n".join(map_lines) if map_lines else ""

        return VHDL_MODULE_TEMPLATE.format(
            module_name=name,
            size=ram_bits,
            data_flow_ports=data_flow,
            core_port_map=core_map,
        )

    def _gen_python_hw(self, name, description, params):
        """Generate Python ModuleBase subclass."""
        class_name = ''.join(w.capitalize() for w in name.split('_'))

        param_list_entries = []
        alias_entries = []
        for i, p in enumerate(params):
            ptype = p.get("type", "int")
            width = 1 if ptype == "bool" else (32 if ptype == "float" else 16)
            param_list_entries.append(
                f"        {i}: {{\"name\": \"{p['key']}\", \"width\": {width}}},"
            )
            alias_entries.append(f"        \"{p['key']}\": {i},")

        param_block = "\n".join(param_list_entries) if param_list_entries else "        # no parameters"
        alias_block = "\n".join(alias_entries) if alias_entries else "        # no aliases"

        code = PYTHON_HW_TEMPLATE.format(
            class_name=class_name,
            description=description,
            parameter_list=f"    parameter_list = {{\n{param_block}\n    }}",
            alias_list=f"    alias_list = {{\n{alias_block}\n    }}",
        )
        # Add import header
        header = (
            "# Generated by FPGA_Agent\n"
            "from module import ModuleBase\n"
            "from bus import Bus\n\n\n"
        )
        return header + code

    def _gen_python_node(self, module_name, display_name, inputs, outputs,
                          max_inst, params):
        """Generate Python NodeItem subclass."""
        class_name = ''.join(w.capitalize() for w in module_name.split('_'))
        short_name = module_name[:4].upper()

        num_inputs = len(inputs)
        num_outputs = len(outputs)
        height = max(60, max(num_inputs, num_outputs) * 28 + 20)

        in_names = [p["name"] for p in inputs]
        out_names = [p["name"] for p in outputs]
        in_displays = [p["display"] for p in inputs]
        out_displays = [p["display"] for p in outputs]
        in_signals = [p["signal"] for p in inputs]
        out_signals = [p["signal"] for p in outputs]

        schema_var = f"_{module_name.upper()}_SCHEMA"

        # For single-instance modules, always use base name
        if max_instances == 1:
            name_init = f'name = "{short_name}"'
        else:
            name_init = (
                f'if index == 0:\n'
                f'            name = "{short_name}"\n'
                f'        else:\n'
                f'            name = f"{short_name}{{index + 1}}"'
            )

        code = PYTHON_NODE_TEMPLATE.format(
            class_name=class_name,
            display_name=display_name,
            short_name=short_name,
            num_inputs=num_inputs,
            num_outputs=num_outputs,
            height=height,
            inputs_list=repr(in_names),
            outputs_list=repr(out_names),
            inputs_display=repr(in_displays),
            outputs_display=repr(out_displays),
            inputs_signals=repr(in_signals),
            outputs_signals=repr(out_signals),
            max_instances=max_inst,
            schema_var=schema_var,
        )
        # Fix the name initialization
        code = code.replace(
            f'name = "{short_name}"\n        super()',
            f'{name_init}\n        super()'
        )

        # Add imports header
        header = (
            "# Generated by FPGA_Agent\n"
            "from PySide6.QtWidgets import QGraphicsItem\n"
            "from qt_module import NodeItem\n"
            f"from generated.schemas import {schema_var}\n\n\n"
        )
        return header + code, class_name, short_name

    def _gen_schema(self, class_name, params):
        """Generate parameter schema list."""
        if not params:
            return (
                f"# Schema for {class_name}\n"
                f"_{class_name.upper()}_SCHEMA = []\n\n"
            )

        entries = []
        for p in params:
            entry = "    {\n"
            entry += f'        "key": "{p["key"]}",\n'
            entry += f'        "label": "{p.get("label", p["key"])}",\n'
            ptype = p.get("type", "int")
            entry += f'        "type": "{ptype}",\n'
            entry += f'        "mode": "direct",\n'
            entry += f'        "free": True,\n'
            if "min" in p:
                entry += f'        "min": {p["min"]},\n'
            if "max" in p:
                entry += f'        "max": {p["max"]},\n'
            if "note" in p:
                entry += f'        "note": "{p["note"]}",\n'
            if "default" in p:
                entry += f'        "default": {repr(p["default"])},\n'
            else:
                entry += f'        "default": {0 if ptype in ("int", "float") else "False"},\n'
            entry += "    }"
            entries.append(entry)

        schema_name = f"_{class_name.upper()}_SCHEMA"
        code = f"# Schema for {class_name}\n{schema_name} = [\n"
        code += ",\n".join(entries)
        code += "\n]\n\n"
        return code

    # ------------------------------------------------------------------
    # Port allocation
    # ------------------------------------------------------------------

    def _alloc_ports(self, inputs, outputs):
        """Allocate port numbers for signal and control ports."""
        signal_in = {}
        signal_out = {}
        ctrl_in = {}
        ctrl_out = {}

        si = self._port_state["next_signal_port"]
        ci = self._port_state["next_control_port"]

        for i, p in enumerate(inputs):
            signals = p.get("signal", [])
            if "bool" in signals and len(signals) == 1:
                ctrl_in[i] = ci
                ci += 1
            else:
                signal_in[i] = si
                si += 1

        for i, p in enumerate(outputs):
            signals = p.get("signal", [])
            if "bool" in signals and len(signals) == 1:
                ctrl_out[i] = ci
                ci += 1
            else:
                signal_out[i] = si
                si += 1

        self._port_state["next_signal_port"] = si
        self._port_state["next_control_port"] = ci

        return signal_in, signal_out, ctrl_in, ctrl_out

    # ------------------------------------------------------------------
    # File I/O helpers
    # ------------------------------------------------------------------

    def _write_module_file(self, module_name, filename, content):
        """Write a file into generated/modules/<module_name>/."""
        mod_dir = _MODULES_DIR / module_name
        mod_dir.mkdir(parents=True, exist_ok=True)
        filepath = mod_dir / filename
        filepath.write_text(content, encoding="utf-8")
        return filepath

    def _append_to_file(self, filepath, content):
        """Append content to a file, adding a separator."""
        existing = filepath.read_text(encoding="utf-8") if filepath.exists() else ""
        if existing and not existing.endswith("\n\n"):
            content = "\n\n" + content
        filepath.write_text(existing + content, encoding="utf-8")

    def _load_port_map(self):
        """Load or initialize port number tracking."""
        if _PORT_MAP_FILE.exists():
            self._port_state = json.loads(_PORT_MAP_FILE.read_text(encoding="utf-8"))
        else:
            self._port_state = {
                "generated_modules": {},
                "next_signal_port": 51,
                "next_control_port": 10,
            }

    def _save_port_map(self):
        """Save port number allocations."""
        _PORT_MAP_FILE.write_text(
            json.dumps(self._port_state, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
